### ISSUE TITLE
Not seperate server for cache service

### ISSUE THREAD

**Issue by Vishal18v** [saurass/tinyurl_server#1]
Wanted to be sure that redis is being scaled along with backend server only. Isn't?
Because there is no separate container for it. Dockerfile /tinyurl-server is being scaled for backend server and redis cache? right?

**Comment by saurass** [comment]
Hello @Vishal18v 

I just noticed that I didn't include the docker-stack deploy files for docker swarm in the repository, which surely can be misleading. I have just included it in the Readme.md file. Please have a look. Files can be found [here](https://drive.google.com/drive/folders/1o5_Zr7cC7_0CUj2ujrIrsomemKMaQh7F?usp=sharing)

The docker-stack has 5 services - tinyurl-server, tinyurl-frontend, tinyurl-clicktrackworker, redis and mongodb.

Each of these services can be scaled individually.

Redis can be scaled easily by clustering. You may want to refer this, in case you are planning to scale your redis server [Scaling Redis Server](https://redis.io/topics/cluster-tutorial)

The same goes for mongoDB as well, You can scale it by making clusters. You can refer this article for help. [Build database cluster with mongoDB](https://www.linode.com/docs/databases/mongodb/build-database-clusters-with-mongodb/).

I am closing this issue : )

**Comment by Vishal18v** [comment]
👍
